# Generated by Django 6.0.2 on 2026-02-04 20:12

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(editable=False, max_length=20, unique=True)),
                ('asunto', models.CharField(help_text='Ej: Solicitud de inscripción al torneo', max_length=200)),
                ('tipo_documento', models.CharField(choices=[('OFI', 'Oficio'), ('SOL', 'Solicitud'), ('CAR', 'Carta'), ('MEM', 'Memorándum'), ('RES', 'Resolución')], default='OFI', max_length=3)),
                ('remitente', models.CharField(help_text='Institución o persona que envía el documento', max_length=150)),
                ('dni_ruc', models.CharField(blank=True, max_length=15, null=True, verbose_name='DNI / RUC')),
                ('area_destino', models.CharField(choices=[('PRES', 'Presidencia'), ('SEC', 'Secretaría General'), ('JUST', 'Comisión de Justicia'), ('COMP', 'Competiciones'), ('LOG', 'Logística')], default='SEC', max_length=4)),
                ('estado', models.CharField(choices=[('REC', 'Recibido'), ('REV', 'En Revisión'), ('DER', 'Derivado'), ('OBS', 'Observado'), ('FIN', 'Finalizado/Archivado')], default='REC', max_length=3)),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='documento')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('recepcionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
