# Generated by Django 6.0.2 on 2026-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='email',
            field=models.EmailField(default='sin_correo@fpf.com', max_length=254, verbose_name='Correo Electrónico'),
            preserve_default=False,
        ),
    ]
