# Generated by Django 6.0.2 on 2026-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_documento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='dni_ruc',
            field=models.CharField(default='00000000', max_length=15, verbose_name='DNI / RUC'),
            preserve_default=False,
        ),
    ]
